# Generated by Django 4.2.25 on 2025-11-09 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 11, 9, 17, 30, 29, 337734), verbose_name='Опубликована'),
        ),
    ]
